---
version: 2
jobs:
  build:
    working_directory: ~/bet-api
    docker:
      - image: circleci/ruby:2.6.4
        environment:
          PGHOST: localhost
          PGUSER: bet_api
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: bet_api
          POSTGRES_DB: bet_api_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Setup bundler 2+
      - run:
          name: setup bundler
          command: |
            gem install bundler

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: bet-api-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: bet-api-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: bundle exec rake db:setup

      - run: bundle exec rubocop

      - run:
          name: Rubycritic
          command: bundle exec rubycritic ./app -p /tmp/rubycritic -f json -f html --no-browser

      - store_artifacts:
          path: /tmp/rubycritic

      - run:
          name: Brakeman
          command: |
            mkdir /tmp/brakeman
            bundle exec brakeman --no-exit-on-warn -o /tmp/brakeman/output.json

      - store_artifacts:
          path: /tmp/brakeman

      - run:
          name: RSpec
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
              circleci tests split --split-by=timings)"
            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/test-results/rspec.xml \
              --format progress \
              $TEST_FILES

      - store_test_results:
          path: /tmp/test-results
